# Build settings for a Next.js project
[build]
  command = "next build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# --- API Proxy Redirect ---
# This rule is crucial for connecting the frontend (Netlify) to the backend (Railway).
# It forwards any request made to /api/* on your Netlify site to your Railway service.
# 
# IMPORTANT: Replace the placeholder URL with your actual Railway app URL.
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-app.up.railway.app/api/:splat" # <-- IMPORTANT: CHANGE THIS URL
  status = 200
  force = true # Ensures this rule is applied before any other routing

# The Next.js plugin handles all other routing, including 404s, so
# the previous /* redirects are no longer needed.

# --- Security Headers ---
# These headers help protect your site from common web vulnerabilities.
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# --- Netlify Plugin for Next.js ---
# This plugin is essential for deploying Next.js sites on Netlify.
# It automatically handles server-side rendering, API routes, and more.
# You will need to install it: npm install @netlify/plugin-nextjs
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect rules for clean URLs and SPA behavior
[[redirects]]
  from = "/dashboard"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/calculator"
  to = "/calculator.html"
  status = 200

[[redirects]]
  from = "/education"
  to = "/education-v2.html"
  status = 200

[[redirects]]
  from = "/portfolio"
  to = "/portfolio-v2.html"
  status = 200

[[redirects]]
  from = "/faq"
  to = "/faq-page.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact-page.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about-page.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog-main-page-fixed.html"
  status = 200

[[redirects]]
  from = "/tools"
  to = "/tools-main.html"
  status = 200

[[redirects]]
  from = "/resources"
  to = "/resources-main.html"
  status = 200

[[redirects]]
  from = "/community"
  to = "/community-main.html"
  status = 200

[[redirects]]
  from = "/newsletter"
  to = "/weekly-newsletter.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/account-login.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/account-register.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy-policy-page.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms-of-service.html"
  status = 200

[[redirects]]
  from = "/disclaimer"
  to = "/investment-disclaimer.html"
  status = 200

# Cache static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# HTML files - shorter cache
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# API routes (for future implementation)
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Form handling (Netlify Forms)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Environment-specific settings
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-sitemap"

[[plugins]]
  package = "netlify-plugin-minify-html"
  [plugins.inputs]
    contexts = ["production"]

# Edge functions (for future use)
[[edge_functions]]
  function = "api-proxy"
  path = "/api/*"

